services:
  bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    # Добавляем политику перезапуска
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # Базе данных тоже нужен авторестарт!
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
